default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: eisgozieh_development

test:
  <<: *default
  database: eisgozieh_test

production:
  <<: *default
  database: eisgozieh_production
  username: eisgozieh
  password: <%= ENV['EISGOZIEH_DATABASE_PASSWORD'] %>
